#*******************************************************************************
# IBM Confidential
# OCO Source Materials
# 5737-J29, 5737-B18
# (C) Copyright IBM Corp. 2020 All Rights Reserved.
# The source code for this program is not  published or otherwise divested of
# its trade secrets, irrespective of what has been deposited with
# the U.S. Copyright Office.
#*******************************************************************************


NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/cacert-0.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/cacert-0.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/cacert-0.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/cacert-0.pem
    OrganizationalUnitIdentifier: orderer 
